### PR TITLE
ci: pin conventional-changelog version

### PR DESCRIPTION
**Pull request by vbarua**

### CODE REVIEW

**Comment by vbarua** [comment]
xref: https://github.com/semantic-release/semantic-release/issues/2929

ibis-substrait was affected by this as well: https://github.com/ibis-project/ibis-substrait/pull/742

**Review by EpsilonPrime — APPROVED** [review]

**Review by gforsyth — APPROVED** [review]
:shipit:

**Comment by gforsyth** [comment]
You can also run the `dry_run` locally and it should spit out the expected changelog since the last release (for a local check)

**Comment by gforsyth** [comment]
Also, just so it isn't a surprise, the `BREAKING CHANGE` commits means the next release will be 1.0.0

**Comment by vbarua** [comment]
> Also, just so it isn't a surprise, the BREAKING CHANGE commits means the next release will be 1.0.0

Should it be 0.16.0 actually? I though breaking changes were allowed pre-1.0?

**Comment by vbarua** [comment]
We've published breaking changes before that only bumped this up by a minor?
https://github.com/substrait-io/substrait-java/releases/tag/v0.15.0

**Comment by gforsyth** [comment]
we might have to summon @cpcloud for his conventional commits expertise

**Comment by vbarua** [comment]
Hmm, it looks like we configure the commit analyser to treat breaking changes as minor version here:
https://github.com/substrait-io/substrait-java/blob/4922c82cfc45de6f86e5e0388bd6a98086ca24b3/.releaserc.json#L13C1-L20C7

It looks like the dry run doesn't have that configured.

**Comment by vbarua** [comment]
Okay it looks like the default rules as defined in https://github.com/semantic-release/commit-analyzer/blob/6026589075daf31928b408527e9e8988c3146f47/lib/default-release-rules.js#L7C38-L7C38
includes
```
{ breaking: true, release: "major" },
```
and we use
```
{"breaking": true, "release": "minor"}
```

Going back in time, I ran a sense check by executing a dry-run on [the commit before the prior chore](https://github.com/substrait-io/substrait-java/commit/68aa7c4782dbede50407d6b9c2cfa739b07b73c6), which is the commit before our 0.15 release.

The output was
```
[10:21:08 AM] [semantic-release] › ℹ  Found git tag v0.14.1 associated with version 0.14.1 on branch tmp.TlLICli74x
[10:21:08 AM] [semantic-release] › ℹ  Found 5 commits since last release
...
[10:21:08 AM] [semantic-release] › ℹ  The next release version is 1.0.0
```

so this appears to be a dry-run artifact.

I feel pretty confident that merging and releasing this isn't about to publish a 1.0 version.

**Comment by vbarua** [comment]
v.0.16.0 was correctly released
https://github.com/substrait-io/substrait-java/releases/tag/v0.16.0

**Comment by gforsyth** [comment]
woo!  nice detective work!

**Pull request merged**
