### PR TITLE
Convert 'or' function call to 'singleOrList' exression

### PR DESCRIPTION
**Pull request by chaojun-zhang**
Convert 'or' call to substrait singleOrList in case of calcite optimize the 'in' expression as 'or' expression.

### CODE REVIEW

**Comment by chaojun-zhang** [comment]
@jacques-n can you take a look this PR?

**Comment by jacques-n** [comment]
I don't think this is the best modification to solve this problem. I think we're actually hitting a Calcite "optimization" which is converting in clause into an or statement (maybe?). I do see the SqlStdOperatorTable has an IN operator so we should figure out why we don't have that here. It could be that we need to turn off some heuristic optimization that Calcite is doing. Have you tried with a larger in clause and still see Calcite convert to an or expression?

**Comment by chaojun-zhang** [comment]
> I don't think this is the best modification to solve this problem. I think we're actually hitting a Calcite "optimization" which is converting in clause into an or statement (maybe?). I do see the SqlStdOperatorTable has an IN operator so we should figure out why we don't have that here. It could be that we need to turn off some heuristic optimization that Calcite is doing. Have you tried with a larger in clause and still see Calcite convert to an or expression?

 Yes, reading code [here](https://github.com/apache/calcite/blob/main/core/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java#L1196)  seems the  in sub query threshold is default to 20  , we can turn off by simple specify the threshold config as 0, but calcite will  optimized the plan  as joinRel with logicalValue right side 
 
 
image

**Comment by JamesRTaylor** [comment]
@chaojun-zhang - wanted to circle back to this. Given Jacques' comment, do you still think this is the correct approach. If so, would you mind rebasing your patch when you have a chance?

**Pull request closed without merging**
