### PR TITLE
[ISTHMUS] Add null function mapping and OpType

### PR DESCRIPTION
**Pull request by Deegue**
Issue: [ISTHMUS] Null value support in filter #61 

IIUC, we just need to add the mapping to Calcite.

### CODE REVIEW

**Comment by jacques-n** [comment]
The optype change doesn't belong here and seems unecessary. OpType has to do with function type resolution, not user operations.

Can you add some test cases for the is null and is not null patterns to make sure this is transforming right? I belive Calcite may have an atypical object tree for those operations (not just simple function calls).

**Comment by Deegue** [comment]
> The optype change doesn't belong here and seems unecessary. OpType has to do with function type resolution, not user operations.
> 
> Can you add some test cases for the is null and is not null patterns to make sure this is transforming right? I belive Calcite may have an atypical object tree for those operations (not just simple function calls).

Thanks for your review, added some test cases and removed unnecessary code.

**Comment by JamesRTaylor** [comment]
Do anymore of the tpc-ds queries pass with this change?

**Comment by jikunshang** [comment]
> Do anymore of the tpc-ds queries pass with this change?

from description from PR #64,  seems these queries are related 
  - No support for `is null` or `is not null` check
    - [40, 44, 49, 75, 76, 77, 78, 80, 93, 97]
    
can update this [file ](https://github.com/substrait-io/substrait-java/blob/main/isthmus/src/test/java/io/substrait/isthmus/TpcdsQueryNoValidation.java#L44) to enable these queries to check.

BTW, anyone can approve running CI workflows?

**Comment by JamesRTaylor** [comment]
After your first commit, CI workflow will run.

**Comment by Deegue** [comment]
Thanks @JamesRTaylor @jikunshang , any more comments? Gentle ping @jacques-n

**Comment by JamesRTaylor** [comment]
> can update this [file ](https://github.com/substrait-io/substrait-java/blob/main/isthmus/src/test/java/io/substrait/isthmus/TpcdsQueryNoValidation.java#L44)to enable these queries to check.

@jikunshang - that was my thinking as well. Please update this PR with the queries from tpc-ds that pass based on this change.

**Comment by Deegue** [comment]
I tested `[40, 44, 49, 75, 76, 77, 78, 80, 93, 97]`, the result is:
**Queries passing:**
`[40, 75, 76, 77, 93, 97]`

**Queries failing:**
`[44, 49, 78, 80]`

image

Failed reason for Q44:
`java.lang.RuntimeException: Not found the corresponding window aggregate function:RANK`

Failed reason for Q49:
`java.lang.RuntimeException: Not found the corresponding window aggregate function:RANK`

Failed reason for Q78:
`java.lang.IllegalArgumentException: Unable to convert call ROUND(i32, i32).`

Failed reason for Q80:
`java.lang.IllegalArgumentException: Unable to convert call ||(char<5>, char<16>).`

cc @JamesRTaylor

**Comment by JamesRTaylor** [comment]
Thanks for testing, @Deegue. Please add the passing tests to be run in the tpc-ds smoke test. I'll update the open issues with the new information about the failures you mentioned. I think we'll be good-to-go after that.

**Comment by Deegue** [comment]
Thanks @JamesRTaylor , passing tests added.

**Review by JamesRTaylor — APPROVED** [review]
Looks great! Thanks so much for the contribution, @Deegue.

**Comment by JamesRTaylor** [comment]
@Deegue - looks like you need to run spotless to fix some formatting issues:
```
Run './gradlew :isthmus:spotlessApply' to fix these violations.
```

**Pull request closed without merging**
