### PR TITLE
feat(isthmus): cli can now output JSON, TEXT and BINARY proto format

### PR DESCRIPTION
**Pull request by vbarua**

### CODE REVIEW

**Comment by vbarua** [comment]
Partial fix for: https://github.com/substrait-io/substrait-java/issues/211

**Comment by EpsilonPrime** [comment]
Technically text is protobuf text.  We are still looking to add the Substrait text format.

**Comment by vbarua** [comment]
@EpsilonPrime good point.

What do you think about the names `PROTOJSON`, `PROTOTEXT` instead of `JSON` and `TEXT` to make it more explicity where they come from?

**Comment by vibhatha** [comment]
@vbarua thank you for working on this.

**Comment by EpsilonPrime** [comment]
That works for me.  The existing implementation can take an explicit format
type and it can also auto detect the type so having some way to eventually
provide auto detect as an option would be nice as well.

**Comment by vbarua** [comment]
@EpsilonPrime @vibhatha 

If these changes look reasonable now, I would appreciate an approval when y'all have a chance 🙇

**Review by vibhatha — APPROVED** [review]
@vbarua LGTM. Thanks for working on this.

**Review by EpsilonPrime — APPROVED** [review]

**Pull request merged**
