### PR TITLE
Implement abstract visitors with fallback method

### PR DESCRIPTION
**Pull request by JamesRTaylor**

### CODE REVIEW

**Review by jinfengni — APPROVED** [review]
lgtm

**Comment by JamesRTaylor** [comment]
FYI, @jacques-n: you can just review/merge https://github.com/substrait-io/substrait-java/pull/27 as this is included there.

**Review by jacques-n — APPROVED** [review]
This looks like it is missing some rels but merging as is.

**Comment by JamesRTaylor** [comment]
Nope, not missing any rels. Thanks for merging.

**Pull request merged**
